//
//  FLGamePresenter.swift
//  FindingLucas
//
//  Created by Guilherme Coelho on 19/07/18.
//  Copyright (c) 2018 DevForFun_Guilherme_Coelho. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FLGamePresenter {
  
  // MARK: - Private properties -
  
  private unowned let view: FLGameViewInterface
  private let interactor: FLGameInteractorInterface
  private let wireframe: FLGameWireframeInterface
  
  // MARK: - Lifecycle -
  
  init(wireframe: FLGameWireframeInterface,
       view: FLGameViewInterface,
       interactor: FLGameInteractorInterface) {
    self.wireframe = wireframe
    self.view = view
    self.interactor = interactor
  }
}

// MARK: - Extensions -

extension FLGamePresenter: FLGamePresenterInterface {
}
