//
//  IntroHomePresenter.swift
//  MobileBanking
//
//  Created by Guilherme Coelho on 28/03/2018.
//  Copyright (c) 2018 BS2. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FLIntroPresenter {
  
  // MARK: - Private properties -
  
  private weak var view: FLIntroViewInterface!
  private let wireframe: FLIntroWireframeInterface

  private let homeCellIdentifier = "HomeCollectionViewCell"
  
  // MARK: - Public properties
  
  // MARK: - Lifecycle -
  
  init(wireframe: FLIntroWireframeInterface,
       view: FLIntroViewInterface) {
    
    self.wireframe = wireframe
    self.view = view
  }
  
}

// MARK: - Extensions -

extension FLIntroPresenter: FLIntroPresenterInterface {
  
  // MARK: - Collection Methods
  
  // MARK: - Wireframe Methods
  
}
