//
//  FLCharSelectionPresenter.swift
//  FindingLucas
//
//  Created by Guilherme Coelho on 19/07/18.
//  Copyright (c) 2018 DevForFun_Guilherme_Coelho. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FLCharSelectionPresenter {
  
  // MARK: - Private properties -
  
  private unowned let view: FLCharSelectionViewInterface
  private let interactor: FLCharSelectionInteractorInterface
  private let wireframe: FLCharSelectionWireframeInterface
  
  // MARK: - Lifecycle -
  
  init(wireframe: FLCharSelectionWireframeInterface,
       view: FLCharSelectionViewInterface,
       interactor: FLCharSelectionInteractorInterface) {
    self.wireframe = wireframe
    self.view = view
    self.interactor = interactor
  }
}

// MARK: - Extensions -

extension FLCharSelectionPresenter: FLCharSelectionPresenterInterface {
}
